@extends('layouts.app')
@section('title', 'My Income')

@section('content')
<div class="max-w-5xl mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold text-gray-900 mb-2">My Income</h1>

    @include('income._tabs')

    {{-- Page note --}}
    <div class="bg-blue-50 border border-blue-200 rounded-xl px-4 py-3 text-sm text-blue-800 mb-6">
        This dashboard shows a live snapshot of your Genos Income. Group BV updates as your Genos members make purchases throughout the day. The 23:59 daily cut-off locks the BV for that day and calculates your Genos Sales Bonus. Your wallet is credited after the cut-off and your earnings are transferred to your bank account every Tuesday. Deductions (3% admin charge, 5% TDS, and any repurchase wallet balance) are applied before transfer.
    </div>

    {{-- Payout hero card --}}
    <div class="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-6 text-white mb-6">
        <p class="text-sm text-indigo-200 font-medium mb-1">Next Payout — Tuesday</p>
        <p class="text-4xl font-bold mb-1">₹—</p>
        <p class="text-sm text-indigo-200">After 3% admin charge + 5% TDS + repurchase deduction</p>
        <p class="text-xs text-indigo-300 mt-2">Your wallet balance will appear here once the GSB engine is active.</p>
    </div>

    {{-- Stat cards --}}
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div class="bg-white rounded-2xl border border-gray-200 p-5">
            <div class="flex items-center justify-between mb-1">
                <p class="text-xs text-gray-500 font-medium">Personal BV (Lifetime)</p>
                <x-help-tip text="The total Business Volume you have accumulated from your own personal purchases since joining. This is a lifetime running total and never resets. It determines your personal purchase title (Retailer, Dealer, Wholesaler, etc.)." />
            </div>
            <p class="text-2xl font-bold text-gray-900">—</p>
            <p class="text-xs text-gray-400 mt-1">No title yet</p>
        </div>
        <div class="bg-white rounded-2xl border border-gray-200 p-5">
            <div class="flex items-center justify-between mb-1">
                <p class="text-xs text-gray-500 font-medium">Left Group BV (Today)</p>
                <x-help-tip text="Total Business Volume generated by all distributors placed in your Left Genos subtree today. Updates as purchases are made." />
            </div>
            <p class="text-2xl font-bold text-gray-900">—</p>
            <p class="text-xs text-gray-400 mt-1">as of last page load</p>
        </div>
        <div class="bg-white rounded-2xl border border-gray-200 p-5">
            <div class="flex items-center justify-between mb-1">
                <p class="text-xs text-gray-500 font-medium">Right Group BV (Today)</p>
                <x-help-tip text="Total Business Volume generated by all distributors placed in your Right Genos subtree today." />
            </div>
            <p class="text-2xl font-bold text-gray-900">—</p>
            <p class="text-xs text-gray-400 mt-1">as of last page load</p>
        </div>
    </div>

    {{-- Carry-forward cards --}}
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div class="bg-white rounded-2xl border border-gray-200 p-5">
            <div class="flex items-center justify-between mb-3">
                <p class="text-sm font-semibold text-gray-700">Power-side Carry-forward</p>
                <x-help-tip text="BV on your stronger (higher) Genos side is carried forward to the next day. Capped at 4,50,000 BV — any BV above this cap is flushed at each cut-off." />
            </div>
            <p class="text-xl font-bold text-gray-900 mb-2">0 BV <span class="text-sm font-normal text-gray-400">/ 4,50,000 BV cap</span></p>
            <div class="w-full bg-gray-100 rounded-full h-2">
                <div class="bg-indigo-500 h-2 rounded-full" style="width: 0%"></div>
            </div>
        </div>
        <div class="bg-white rounded-2xl border border-gray-200 p-5">
            <div class="flex items-center justify-between mb-3">
                <p class="text-sm font-semibold text-gray-700">Slab-1 Weaker Carry-forward</p>
                <x-help-tip text="For the first slab only (15,000 BV match), your weaker side BV carries forward indefinitely — there is no time limit. It accumulates day by day until 15,000 BV is matched and your first ₹1,000 Genos Sales Bonus is earned." />
            </div>
            <p class="text-xl font-bold text-gray-900 mb-2">0 BV <span class="text-sm font-normal text-gray-400">/ 15,000 BV target</span></p>
            <div class="w-full bg-gray-100 rounded-full h-2">
                <div class="bg-green-500 h-2 rounded-full" style="width: 0%"></div>
            </div>
            <p class="text-xs text-gray-400 mt-2">No time limit</p>
        </div>
    </div>
</div>
@endsection
