/**
 * Report exports (XLSX + CSV) - Browser Tests
 *
 * Covers the ReportExport facade rollout (slice S10 of
 * docs/plans/csv-to-xlsx-exports-2026-09-12.md): every human-facing report
 * download now offers both `.xlsx` (default) and `.csv` (?format=csv, or the
 * legacy ?export=csv on the inventory reports), off the same URL, with the
 * same permission gate as before the refactor.
 *
 * Requires:
 *   - App running at APP_URL (default http://localhost:8084)
 *   - admin@arovolife.test / admin12345 (see fixtures.js)
 *   - A11Y_ADN / A11Y_PASSWORD env vars pointing at a distributor in the dev
 *     database (fixtures.js falls back to a default ADN that may not exist
 *     after a reseed)
 *   - At least one weekly payout batch for T12 (NEFT export) - if none
 *     exists the test is skipped rather than failed, since payout batches
 *     are generated by the weekly cut-off job and a fresh dev database may
 *     not have run it yet
 */

import { test, expect } from './fixtures.js';

test.describe.configure({ mode: 'serial' });

// ---------------------------------------------------------------------------
// T1-T3, T16, T17 - Inventory reports (P1)
// ---------------------------------------------------------------------------

test.describe('Inventory reports export', () => {
    test('T1: stock-on-hand -> Export Excel downloads .xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/inventory/reports/stock-on-hand');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Export Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toBe('inventory-stock-on-hand.xlsx');
    });

    test('T2: stock-on-hand shows both Export Excel and CSV buttons', async ({ adminPage: page }) => {
        await page.goto('/admin/inventory/reports/stock-on-hand');
        await expect(page.getByRole('link', { name: 'Export Excel' })).toBeVisible();
        await expect(page.getByRole('link', { name: 'CSV', exact: true })).toBeVisible();
    });

    test('T3: valuation -> Export Excel downloads inventory-valuation.xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/inventory/reports/valuation');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Export Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toBe('inventory-valuation.xlsx');
    });

    test('T16: legacy ?export=csv still downloads CSV', async ({ adminPage: page }) => {
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.goto('/admin/inventory/reports/stock-on-hand?export=csv'),
        ]);
        expect(download.suggestedFilename()).toBe('inventory-stock-on-hand.csv');
    });

    test('T17: stock-on-hand -> CSV button downloads .csv', async ({ adminPage: page }) => {
        await page.goto('/admin/inventory/reports/stock-on-hand');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'CSV', exact: true }).click(),
        ]);
        expect(download.suggestedFilename()).toBe('inventory-stock-on-hand.csv');
    });
});

// ---------------------------------------------------------------------------
// T4, T18, T20, T21 - GSB calculation (P6)
// ---------------------------------------------------------------------------

test.describe('Compensation: GSB calculation export', () => {
    test('T4: Download Excel matches gsb-calculation-YYYY-MM-DD.xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/compensation/gsb-calculation');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Download Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/^gsb-calculation-\d{4}-\d{2}-\d{2}\.xlsx$/);
    });

    test('T18: CSV button downloads .csv', async ({ adminPage: page }) => {
        await page.goto('/admin/compensation/gsb-calculation');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'CSV', exact: true }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.csv$/);
    });

    test('T20: bare export URL (no format param) downloads .xlsx, not .csv', async ({ adminPage: page }) => {
        // Unlike the inventory reports (whose route serves both the HTML
        // report page and the export, switching on the presence of
        // ?export=/?format=), the GSB calculation export lives at its own
        // dedicated URL (.../gsb-calculation/export) which always streams a
        // file. Hitting it with no query params at all directly tests D2's
        // default-to-XLSX behaviour.
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.goto('/admin/compensation/gsb-calculation/export'),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });

    test('T21: CSV button preserves an active filter query param', async ({ adminPage: page }) => {
        // Apply a status filter, then check the CSV anchor's href still
        // carries it, not only the export-format param.
        await page.goto('/admin/compensation/gsb-calculation?status=credited');
        const href = await page.getByRole('link', { name: 'CSV', exact: true }).getAttribute('href');
        expect(href).toContain('status=credited');
        expect(href).toContain('format=csv');
    });
});

// ---------------------------------------------------------------------------
// T5 - Rank bonus calculation (P6)
// ---------------------------------------------------------------------------

test.describe('Compensation: rank bonus calculation export', () => {
    test('T5: Download Excel downloads an .xlsx file', async ({ adminPage: page }) => {
        await page.goto('/admin/compensation/rb-calculation');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Download Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });
});

// ---------------------------------------------------------------------------
// T6 - BV ledger export (P3) - converted (S6b: lazy/cursor iteration)
// ---------------------------------------------------------------------------

test.describe('Commerce: BV ledger export', () => {
    test('T6: Export Excel downloads .xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/commerce/bv-ledger');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Export Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });

    test('T6: CSV button downloads .csv', async ({ adminPage: page }) => {
        await page.goto('/admin/commerce/bv-ledger');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'CSV', exact: true }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.csv$/);
    });
});

// ---------------------------------------------------------------------------
// T7 - Distributors / DSR register (P2)
// ---------------------------------------------------------------------------

test.describe('Admin distributors: DSR register export', () => {
    test('T7: Export Excel (DSR Register) downloads register-of-direct-sellers-*.xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/distributors');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: /Export Excel \(DSR Register\)/ }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/^register-of-direct-sellers-.*\.xlsx$/);
    });
});

// ---------------------------------------------------------------------------
// T8 - Grievance report (P5)
// ---------------------------------------------------------------------------

test.describe('Grievance report export', () => {
    test('T8: Export 12 months (Excel) downloads .xlsx', async ({ adminPage: page }) => {
        await page.goto('/admin/grievances/report');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Export 12 months (Excel)' }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });
});

// ---------------------------------------------------------------------------
// T9, T19 - Income: GSB history (P7)
// ---------------------------------------------------------------------------

test.describe('Income: GSB history export', () => {
    test('T9: Excel button downloads .xlsx', async ({ distributorPage: page }) => {
        await page.goto('/income/gsb-history');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: /Excel/ }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });

    test('T19: CSV button downloads .csv', async ({ distributorPage: page }) => {
        await page.goto('/income/gsb-history');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'CSV', exact: true }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.csv$/);
    });
});

// ---------------------------------------------------------------------------
// T10 - Income: wallet (P8)
// ---------------------------------------------------------------------------

test.describe('Income: wallet export', () => {
    test('T10: Excel button downloads .xlsx', async ({ distributorPage: page }) => {
        await page.goto('/income/wallet');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: /Excel/ }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });
});

// ---------------------------------------------------------------------------
// T11 - Dashboard: My Team roster (P9)
// ---------------------------------------------------------------------------

test.describe('Dashboard: My Team roster export', () => {
    test('T11: Download Excel (from the team-roster modal) downloads .xlsx', async ({ distributorPage: page }) => {
        await page.goto('/dashboard');
        const totalCard = page.locator('[data-team-roster="total"]');
        if ((await totalCard.count()) === 0) {
            test.skip(true, 'My Team card not present for this distributor - no team stats to show');
        }
        await totalCard.click();
        await expect(page.locator('#team-roster-modal')).toBeVisible();
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.locator('#team-roster-download').click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
    });
});

// ---------------------------------------------------------------------------
// T12 - NEFT export (P10) - must STILL be CSV (negative test on the exemption)
// ---------------------------------------------------------------------------

test.describe('Payout batch: NEFT export stays CSV', () => {
    test('T12: NEFT bank-file download is still .csv', async ({ adminPage: page }) => {
        await page.goto('/admin/compensation/weekly-payouts');
        const firstBatchLink = page.locator('tbody a[href*="/admin/compensation/weekly-payouts/"]').first();
        if ((await firstBatchLink.count()) === 0) {
            test.skip(true, 'No weekly payout batch exists in this dev database - the weekly cut-off job has not run yet');
        }
        await firstBatchLink.click();
        const neftLink = page.getByRole('link', { name: /Download bank file \(NEFT\)/ });
        if ((await neftLink.count()) === 0) {
            test.skip(true, 'Batch is not in a state that exposes the NEFT download link (e.g. not yet signed off)');
        }
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            neftLink.click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.csv$/);
    });
});

// ---------------------------------------------------------------------------
// T13, T14 - Permission negatives: distributor hitting admin export URLs
// ---------------------------------------------------------------------------

test.describe('Permission negatives', () => {
    test('T13: distributor hitting an admin inventory export URL is refused', async ({ distributorPage: page }) => {
        const response = await page.goto('/admin/inventory/reports/stock-on-hand?export=xlsx');
        expect([403, 302]).toContain(response.status());
        if (response.status() === 302) {
            // Redirects (e.g. to /login) must not land the distributor on the
            // report itself.
            await page.waitForLoadState('domcontentloaded');
            expect(page.url()).not.toContain('/admin/inventory/reports/stock-on-hand');
        }
    });

    test('T14: distributor hitting the GSB calculation export URL is refused', async ({ distributorPage: page }) => {
        const response = await page.goto('/admin/compensation/gsb-calculation/export');
        expect([403, 302]).toContain(response.status());
        if (response.status() === 302) {
            await page.waitForLoadState('domcontentloaded');
            expect(page.url()).not.toContain('/admin/compensation/gsb-calculation/export');
        }
    });
});

// ---------------------------------------------------------------------------
// T15 - Zero-row report still downloads (no 500)
// ---------------------------------------------------------------------------

test.describe('Edge case: zero-row export', () => {
    test('T15: a filter that yields zero rows still downloads without a 500', async ({ adminPage: page }) => {
        // An implausible warehouse-code filter on stock-on-hand should return
        // no matching rows while the export endpoint itself still streams a
        // valid file rather than erroring.
        await page.goto('/admin/inventory/reports/stock-on-hand?warehouse_code=ZZZ-DOES-NOT-EXIST');
        const [download] = await Promise.all([
            page.waitForEvent('download'),
            page.getByRole('link', { name: 'Export Excel' }).click(),
        ]);
        expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
        const failure = await download.failure();
        expect(failure).toBeNull();
    });
});
