<?php

declare(strict_types=1);

namespace App\Modules\Compensation\Services;

use App\Modules\Compensation\Models\AdcBonusResult;
use App\Modules\Compensation\Models\AreteCenter;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Arete Development Center Bonus engine.
 *
 * Earning: configurable % (default 3%) on the net member BV (refunds deducted)
 * generated by all active members of each center in the month.
 * Cap: configurable (default ₹1,00,000/month); a per-center
 * `monthly_cap_override_paise` may lower (never raise) it — KP's
 * development-phase penalty for centers that crossed a phase level without
 * proving the facility upgrade.
 * Admin charge + TDS: applied at payout time, not at credit time.
 * Rate, cap, admin charge and TDS are all admin-editable.
 * Paid to: the center's assigned distributor.
 */
final class AreteDevelopmentCenterBonusService
{
    public function __construct(
        private readonly WalletService $wallet,
        private readonly CompensationPlanSettingsService $plan,
    ) {}

    /**
     * Calculate and credit ADC Bonus for all active centers in the month.
     * Idempotent: skips centers already credited for the month.
     *
     * @return array{credited: int, skipped_no_bv: int, skipped_net_negative: int, total_net_paise: int}
     */
    public function runForMonth(Carbon $month): array
    {
        $monthStart = $month->copy()->startOfMonth()->toDateString();
        $monthEnd = $month->copy()->endOfMonth()->toDateString();

        $centers = AreteCenter::where('status', AreteCenter::STATUS_ACTIVE)->get();

        $credited = 0;
        $skippedNoBv = 0;
        $skippedNetNegative = 0;
        $totalNet = 0;

        DB::transaction(function () use ($centers, $monthStart, $monthEnd, &$credited, &$skippedNoBv, &$skippedNetNegative, &$totalNet): void {
            foreach ($centers as $center) {
                $alreadyCredited = AdcBonusResult::where('center_id', $center->id)
                    ->where('month_start', $monthStart)
                    ->where('status', AdcBonusResult::STATUS_CREDITED)
                    ->exists();

                if ($alreadyCredited) {
                    continue;
                }

                // Company-default centre has no assigned distributor yet — skip payout.
                if ($center->assigned_distributor_id === null) {
                    continue;
                }

                // Find active members for this month.
                $memberIds = DB::table('arete_center_members')
                    ->where('center_id', $center->id)
                    ->where('effective_from', '<=', $monthEnd)
                    ->where(fn ($q) => $q->whereNull('effective_to')->orWhere('effective_to', '>=', $monthStart))
                    ->pluck('distributor_id');

                if ($memberIds->isEmpty()) {
                    $skippedNoBv++;

                    continue;
                }

                // Sum the net member BV for the month. `bv_paise` is signed
                // (+ accrual, − reversal), so an unfiltered SUM deducts the
                // month's refunds — the centre is not paid on reversed sales.
                $totalBv = (int) DB::table('bv_ledger_entries')
                    ->whereIn('distributor_id', $memberIds)
                    ->whereBetween('effective_at', [$monthStart.' 00:00:00', $monthEnd.' 23:59:59'])
                    ->sum('bv_paise');

                // A refund-heavy month can net to zero or below — nothing to
                // pay either way, but the two cases are counted apart: a
                // net-negative centre sold and then refunded, which is worth
                // surfacing separately from a centre that simply had no sales.
                if ($totalBv < 0) {
                    $skippedNetNegative++;

                    continue;
                }

                if ($totalBv === 0) {
                    $skippedNoBv++;

                    continue;
                }

                // Per-center override implements KP's development-phase
                // penalty (2026-08-07): a center that crossed a phase level
                // without emailing proof of the upgrade is held to a lower
                // slab income. The override can only lower the standard cap,
                // never raise it — the plan cap is a hard ceiling.
                $gross = $this->grossFor($totalBv, $center->monthly_cap_override_paise)['gross_paise'];
                $result = AdcBonusResult::updateOrCreate(
                    [
                        'center_id' => $center->id,
                        'month_start' => $monthStart,
                    ],
                    [
                        'distributor_id' => $center->assigned_distributor_id,
                        'member_count' => $memberIds->count(),
                        'total_member_bv_paise' => $totalBv,
                        'gross_paise' => $gross,
                        'admin_charge_paise' => 0,
                        'tds_paise' => 0,
                        'net_paise' => $gross,
                        'status' => AdcBonusResult::STATUS_PENDING,
                    ],
                );

                // Credit the wallet only when there is something to pay.
                if ($gross > 0) {
                    $this->wallet->credit(
                        distributorId: $center->assigned_distributor_id,
                        amountPaise: $gross,
                        type: 'adc_credit',
                        referenceId: $result->id,
                        referenceType: 'adc_bonus_result',
                        memo: 'Arete Dev Center Bonus — '.$center->name.' '.$monthStart,
                    );

                    $totalNet += $gross;
                }

                // Always finalize to CREDITED so the idempotency guard (which
                // matches CREDITED) terminates the result on re-runs, even when
                // net is zero (deductions exhausted the gross). A zero-net
                // result simply carries no wallet entry.
                $result->update([
                    'status' => AdcBonusResult::STATUS_CREDITED,
                    'credited_at' => now(),
                ]);

                $credited++;
            }
        });

        return [
            'credited' => $credited,
            'skipped_no_bv' => $skippedNoBv,
            'skipped_net_negative' => $skippedNetNegative,
            'total_net_paise' => $totalNet,
        ];
    }

    /**
     * The ADC arithmetic, in one place for the engine and the admin report:
     * flat = ⌊ member BV × rate ⌋, gross = min(flat, cap), where a centre's
     * own override may only LOWER the plan cap (the plan cap is a ceiling).
     *
     * @return array{flat_paise: int, cap_paise: int, gross_paise: int}
     */
    public function grossFor(int $memberBvPaise, ?int $capOverridePaise): array
    {
        $capPaise = $this->plan->adcCapPaise();
        if ($capOverridePaise !== null) {
            $capPaise = min($capPaise, $capOverridePaise);
        }

        $flat = max(0, (int) floor($memberBvPaise * $this->plan->adcRateBp() / 10_000));

        return [
            'flat_paise' => $flat,
            'cap_paise' => $capPaise,
            'gross_paise' => min($flat, $capPaise),
        ];
    }
}
