<?php

declare(strict_types=1);

namespace App\Modules\Compensation\Services;

use App\Modules\Compensation\Enums\BonusType;
use App\Modules\Compensation\Models\AdcBonusResult;
use App\Modules\Compensation\Models\AreteCenter;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Arete Development Center Bonus engine.
 *
 * Earning: configurable % (default 3%) on BV generated by all active members
 * of each center in the month. Cap: configurable (default ₹1,00,000/month).
 * Admin charge + TDS: applied via BonusDeductionService (KP 2026-06-27 brought
 * ADC into the admin-charge scope; the scope stays admin-toggleable).
 * Rate, cap, admin charge and TDS are all admin-editable.
 * Paid to: the center's assigned distributor.
 */
final class AreteDevelopmentCenterBonusService
{
    public function __construct(
        private readonly WalletService $wallet,
        private readonly CompensationPlanSettingsService $plan,
        private readonly BonusDeductionService $deductions,
    ) {}

    /**
     * Calculate and credit ADC Bonus for all active centers in the month.
     * Idempotent: skips centers already credited for the month.
     *
     * @return array{credited: int, skipped_no_bv: int, total_net_paise: int}
     */
    public function runForMonth(Carbon $month): array
    {
        $monthStart = $month->copy()->startOfMonth()->toDateString();
        $monthEnd = $month->copy()->endOfMonth()->toDateString();

        $centers = AreteCenter::where('status', AreteCenter::STATUS_ACTIVE)->get();

        $credited = 0;
        $skippedNoBv = 0;
        $totalNet = 0;

        DB::transaction(function () use ($centers, $monthStart, $monthEnd, &$credited, &$skippedNoBv, &$totalNet): void {
            foreach ($centers as $center) {
                $alreadyCredited = AdcBonusResult::where('center_id', $center->id)
                    ->where('month_start', $monthStart)
                    ->where('status', AdcBonusResult::STATUS_CREDITED)
                    ->exists();

                if ($alreadyCredited) {
                    continue;
                }

                // Find active members for this month.
                $memberIds = DB::table('arete_center_members')
                    ->where('center_id', $center->id)
                    ->where('effective_from', '<=', $monthEnd)
                    ->where(fn ($q) => $q->whereNull('effective_to')->orWhere('effective_to', '>=', $monthStart))
                    ->pluck('distributor_id');

                if ($memberIds->isEmpty()) {
                    $skippedNoBv++;

                    continue;
                }

                // Sum member BV accrued in the month.
                $totalBv = (int) DB::table('bv_ledger_entries')
                    ->where('type', 'accrual')
                    ->whereIn('distributor_id', $memberIds)
                    ->whereBetween('effective_at', [$monthStart.' 00:00:00', $monthEnd.' 23:59:59'])
                    ->sum('bv_paise');

                if ($totalBv === 0) {
                    $skippedNoBv++;

                    continue;
                }

                $gross = min(
                    (int) floor($totalBv * $this->plan->adcRateBp() / 10_000),
                    $this->plan->adcCapPaise(),
                );
                $deduction = $this->deductions->for(BonusType::Arete, $gross);

                $result = AdcBonusResult::updateOrCreate(
                    [
                        'center_id' => $center->id,
                        'month_start' => $monthStart,
                    ],
                    [
                        'distributor_id' => $center->assigned_distributor_id,
                        'member_count' => $memberIds->count(),
                        'total_member_bv_paise' => $totalBv,
                        'gross_paise' => $gross,
                        'admin_charge_paise' => $deduction->adminChargePaise,
                        'tds_paise' => $deduction->tdsPaise,
                        'net_paise' => $deduction->netPaise,
                        'status' => AdcBonusResult::STATUS_PENDING,
                    ],
                );
                $net = $deduction->netPaise;

                // Credit the wallet only when there is something to pay.
                if ($net > 0) {
                    $this->wallet->credit(
                        distributorId: $center->assigned_distributor_id,
                        amountPaise: $net,
                        type: 'adc_credit',
                        referenceId: $result->id,
                        referenceType: 'adc_bonus_result',
                        memo: 'Arete Dev Center Bonus — '.$center->name.' '.$monthStart,
                    );

                    $totalNet += $net;
                }

                // Always finalize to CREDITED so the idempotency guard (which
                // matches CREDITED) terminates the result on re-runs, even when
                // net is zero (deductions exhausted the gross). A zero-net
                // result simply carries no wallet entry.
                $result->update([
                    'status' => AdcBonusResult::STATUS_CREDITED,
                    'credited_at' => now(),
                ]);

                $credited++;
            }
        });

        return [
            'credited' => $credited,
            'skipped_no_bv' => $skippedNoBv,
            'total_net_paise' => $totalNet,
        ];
    }
}
