CREATE TABLE distributors (
    id                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                         BIGINT UNSIGNED NOT NULL,
    adn                             VARCHAR(16)  NOT NULL,
    pan_hash                        BINARY(32)   NOT NULL,
    pan_last4                       CHAR(4)      NOT NULL,
    aadhaar_ref                     VARCHAR(64)  NULL,
    aadhaar_last4                   CHAR(4)      NULL,
    bank_account_enc                VARBINARY(512) NOT NULL,
    bank_ifsc                       CHAR(11)     NOT NULL,
    sponsor_id                      BIGINT UNSIGNED NOT NULL,
    placement_id_at_registration    BIGINT UNSIGNED NULL,
    placement_parent_id             BIGINT UNSIGNED NOT NULL,
    placement_side                  ENUM('L','R') NOT NULL,
    placement_strategy_snapshot     ENUM('default_left','default_right','custom') NOT NULL,
    side_chosen_by                  ENUM('admin_default','sponsor_override','prospect_custom') NOT NULL,
    depth                           INT UNSIGNED NOT NULL,
    effective_date                  DATETIME(3) NOT NULL,
    cooling_off_end_at              DATETIME(3) NOT NULL,
    state                           VARCHAR(64)  NOT NULL,
    spouse_distributor_id           BIGINT UNSIGNED NULL,
    is_primary_couple               TINYINT(1)   NOT NULL DEFAULT 0,
    created_at                      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uniq_distributors_user (user_id),
    UNIQUE KEY uniq_distributors_adn  (adn),
    UNIQUE KEY uniq_distributors_pan  (pan_hash),
    UNIQUE KEY uniq_distributors_slot (placement_parent_id, placement_side),
    KEY idx_distributors_sponsor      (sponsor_id),
    KEY idx_distributors_state        (state),
    CONSTRAINT fk_distributors_user    FOREIGN KEY (user_id)             REFERENCES users(id)        ON DELETE RESTRICT,
    CONSTRAINT fk_distributors_sponsor FOREIGN KEY (sponsor_id)          REFERENCES distributors(id) ON DELETE RESTRICT,
    CONSTRAINT fk_distributors_parent  FOREIGN KEY (placement_parent_id) REFERENCES distributors(id) ON DELETE RESTRICT,
    CONSTRAINT fk_distributors_spouse  FOREIGN KEY (spouse_distributor_id) REFERENCES distributors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
