<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('franchises', function (Blueprint $table): void {
            $table->id();

            $table->foreignId('operator_distributor_id')
                ->constrained('distributors')
                ->cascadeOnDelete();

            $table->foreignId('arete_center_id')
                ->nullable()
                ->constrained('arete_centers')
                ->nullOnDelete();

            /**
             * Unique franchise code assigned at application time
             * (e.g. ARV-FR-000001). Generated by FranchiseCodeGenerator.
             */
            $table->string('code', 32)->unique();

            /**
             * Lifecycle states:
             *   pending_approval → active (admin approves)
             *   pending_approval → rejected (admin rejects)
             *   active → suspended (compliance action)
             */
            $table->string('status', 32)->default('pending_approval');

            // Location of the proposed franchise outlet.
            $table->string('address_line', 255)->nullable();
            $table->char('pincode', 6)->nullable();
            $table->string('district', 100)->nullable();
            $table->string('state', 100)->nullable();

            // Free-text motivation / notes from the applicant.
            $table->text('notes')->nullable();

            // Admin decision fields.
            $table->text('admin_notes')->nullable();
            $table->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('reviewed_at')->nullable();

            $table->timestamp('applied_at')->nullable();
            $table->timestamp('activated_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('franchises');
    }
};
